J#45313: Added targetConstraint extension, deprecated cqf-targetInvar…
HL7/fhir-extensions pull request #102
Opened 2024-04-21 15:27 UTC by brynrhodes

…iant and questionnaire-constraint

2024-04-21 17:17 UTC, lmckenzi requested changes
type for requirements should be markdown, not string.
Our binding for severity should also allow bestPractice, as the extension for it won't be allowed here.  (Alternatively, change the scope of the extension to be allowed here)

2024-04-23 03:32 UTC, brynrhodes commented
I opted to allow the bestPractice extensions to be used here because the constraintSeverity value set doesn't have a code for best practice, even in the latest build of FHIR.

2024-04-24 07:41 UTC, grahamegrieve approved these changes
ok

2024-04-24 16:36 UTC, lmckenzi approved these changes

2024-04-24 16:37 UTC, merged