]StructureDefinition-cqf-notDoneReason creation
HL7/fhir-extensions pull request #111
Opened 2024-06-28 17:19 UTC by bryantaustin13

Part of https://jira.hl7.org/browse/FHIR-45369 Update QI-Core to use extensions pack

for cqf-notDoneReason

2024-07-10 18:54 UTC, brynrhodes requested changes
Please tighten the extension context to Observation

2024-07-10 18:54 UTC, brynrhodes commented on input/definitions/StructureDefinition/StructureDefinition-cqf-notDoneReason.json
> +      "expression" : "Resource"
For notDoneReason, what resources specifically do we expect this to be usable on? In QICore, this is only in the ObservationCancelled profile, so is Observation the only one? I'd say let's start there

2024-07-10 19:00 UTC, brynrhodes commented on input/definitions/StructureDefinition/StructureDefinition-cqf-notDoneReason.json
> +          "value" : "http://www.hl7.org/Special/committees/fiwg"
```suggestion
          "value" : "http://www.hl7.org/Special/committees/cqi"
```

2024-07-10 19:01 UTC, brynrhodes commented on input/definitions/StructureDefinition/StructureDefinition-cqf-notDoneReason.json
> +{
Also, please move the definition to the definitions/Resource folder

2024-07-10 19:13 UTC, brynrhodes commented on input/definitions/StructureDefinition/StructureDefinition-cqf-notDoneReason.json
> +          "code" : "US"
Remove this jurisdiction, it's not appropriate in the extensions pack

2024-07-10 19:14 UTC, brynrhodes commented on input/definitions/StructureDefinition/StructureDefinition-cqf-notDoneReason.json
> +          "valueSet" : "http://terminology.hl7.org/ValueSet/POAIndicators"
This should actually be a binding to the same negationValueSetExample created in the doNotPerformReason extension

2024-07-11 16:09 UTC, bryantaustin13 commented
All change requests completed.

2024-07-15 04:06 UTC, brynrhodes requested changes
A few more minor tweaks

2024-07-15 04:06 UTC, brynrhodes commented on input/definitions/Resource/ValueSet-negation-reason-example.json
> +      "valueCode": "fhir"
```suggestion
      "valueCode": "cqi"
```

2024-07-15 04:06 UTC, brynrhodes commented on input/definitions/Resource/ValueSet-negation-reason-example.json
> +  "date": "2024-07-01",
```suggestion
  "date": "2024-07-01",
  "publisher" : "HL7 International / Clinical Quality Information",
  "contact": [
    {
      "name" : "Clinical Quality Information WG",
      "telecom": [
        {
          "system": "url",
          "value" : "http://www.hl7.org/Special/committees/cqi"
        }
      ]
    }
  ],
```

2024-07-15 04:07 UTC, brynrhodes approved these changes

2024-07-23 15:26 UTC, brynrhodes commented
Based on discussion with FHIR-I, this extension is not required, instead the profiles for ServiceRequest and DeviceRequest in QICore should use the `reason` element to indicate the reason for not performing the request

2024-07-23 15:26 UTC, closed without merging