Structure definition cqf do not perform reason
HL7/fhir-extensions pull request #113
Opened 2024-07-03 19:50 UTC by bryantaustin13

for [FHIR-45369](https://jira.hl7.org/browse/FHIR-45369) Do not perform Reason
StructureDefinition along with ValueSet and CodeSystem to support it.

2024-07-10 19:12 UTC, brynrhodes requested changes

2024-07-10 19:12 UTC, brynrhodes commented on input/definitions/Resource/CodeSystem-negation-reason-example.json
> +      "valueCode": "fhir"
```suggestion
      "valueCode": "cqi"
```

2024-07-10 19:12 UTC, brynrhodes commented on input/definitions/Resource/CodeSystem-negation-reason-example.json
> +  "description": "A temporary code system to avoid a qicore binding in StructureDefinition-cqf-doNotPerformReason.",
```suggestion
  "description": "An example code system to illustrate the types of codes that are expected in the doNotPerformReson extension",
```

2024-07-10 19:12 UTC, brynrhodes commented on input/definitions/Resource/CodeSystem-negation-reason-example.json
> +{
Actually, remove this whole CodeSystem, it is not necessary, we only need to create a ValueSet example with a few of the codes from the negationReasonCodes value set in QICore

2024-07-10 19:12 UTC, brynrhodes commented on input/definitions/Resource/StructureDefinition-cqf-doNotPerformReason.json
> +          "value": "http://www.hl7.org/Special/committees/fiwg"
```suggestion
          "value": "http://www.hl7.org/Special/committees/cqi"
```

2024-07-10 19:12 UTC, brynrhodes commented on input/definitions/Resource/StructureDefinition-cqf-doNotPerformReason.json
> +  "publisher": "HL7 International / FHIR Infrastructure",
```suggestion
  "publisher": "HL7 International / Clinical Quality Information",
```

2024-07-10 19:12 UTC, brynrhodes commented on input/definitions/Resource/StructureDefinition-cqf-doNotPerformReason.json
> +      "expression": "StructureDefinition"
This should not be StructureDefinition, this should be limited to those resources we used it on in QICore profiles:
DeviceRequest and ServiceRequest

2024-07-10 19:12 UTC, brynrhodes commented on input/definitions/Resource/ValueSet-negation-reason-example.json
> +    "valueCode": "fhir"
```suggestion
    "valueCode": "cqi"
```

2024-07-10 19:12 UTC, brynrhodes commented on input/definitions/Resource/ValueSet-negation-reason-example.json
> +    }
Was this identifier present in QICore? If so, it should be removed, this is a new extension, let the FHIR Extensions IG assign an OID for it

2024-07-10 19:12 UTC, brynrhodes commented on input/definitions/Resource/StructureDefinition-cqf-doNotPerformReason.json
> +          "code": "US"
Remove this jurisdiction, it's not appropriate in the extensions pack

2024-07-10 19:12 UTC, brynrhodes commented on input/definitions/Resource/StructureDefinition-cqf-doNotPerformReason.json
> +          "strength": "extensible",
```suggestion
          "strength": "example",
```

2024-07-10 19:12 UTC, brynrhodes commented on input/definitions/Resource/ValueSet-negation-reason-example.json
> +        "system": "http://cts.nlm.nih.gov/fhir/ValueSet/2.16.840.1.113762.1.4.1021.56"
Don't reference the VSAC value set here, include the first 3 of the specific SNOMED codes in the expansion of the QICore value set:

https://hl7.org/fhir/us/qicore/ValueSet-qicore-negation-reason.html#expansion

2024-07-10 19:12 UTC, brynrhodes commented on input/definitions/Resource/ValueSet-negation-reason-example.json
> +  "description": "Codes for the reason the event did not occur or was not performed.",
```suggestion
  "description": "An example value set illustrating the kinds of codes that would be expected to be used to indicate the reason an event did not occur, or a request was not performed.",
```

2024-07-11 17:48 UTC, bryantaustin13 commented
This should be ready to be reviewed again.

2024-07-15 04:12 UTC, brynrhodes requested changes

2024-07-15 04:12 UTC, brynrhodes commented on input/definitions/Resource/ValueSet-negation-reason-example.json
> +      "valueCode": "fhir"
```suggestion
      "valueCode": "cqi"
```

2024-07-15 04:12 UTC, brynrhodes commented on input/definitions/Resource/ValueSet-negation-reason-example.json
> +  "description": "An example value set illustrating the kinds of codes that would be expected to be used to indicate the reason an event did not occur, or a request was not performed.",
```suggestion
  "description": "An example value set illustrating the kinds of codes that would be expected to be used to indicate the reason an event did not occur, or a request was not performed.",
  "publisher" : "HL7 International / Clinical Quality Information",
  "contact": [
    {
      "name" : "Clinical Quality Information WG",
      "telecom": [
        {
          "system": "url",
          "value" : "http://www.hl7.org/Special/committees/cqi"
        }
      ]
    }
  ],
```

2024-07-15 04:12 UTC, brynrhodes commented on input/definitions/Resource/StructureDefinition-cqf-doNotPerformReason.json
> +      "expression": "StructureDefinition"
```suggestion
      "expression": "DeviceRequest"
    }, {
      "type": "element",
      "expression": "ServiceRequest"
```

2024-07-15 04:13 UTC, brynrhodes approved these changes

2024-07-23 15:27 UTC, brynrhodes commented
Based on discussion with FHIR-I, this extension is not required, the `reason` element of the ServiceRequest and DeviceRequest resources should be used to capture the reason for not performing the activity.

2024-07-23 15:27 UTC, closed without merging