Jdlnolen extensions r6
HL7/fhir-extensions pull request #114
Opened 2024-07-05 18:42 UTC by jdlnolen

OO extension work for R6

2024-07-15 17:59 UTC, lmckenzi requested changes
Rejection doesn't happen on the ServiceRequest, it happens via Task - and there's already a statusReason there.  A given ServiceRequest might be rejected by 2 different performers and accepted by a third.  Don't think this extension makes sense to add.

2024-07-27 05:15 UTC, grahamegrieve reviewed
why are you making this change?

2024-07-29 17:53 UTC, jdlnolen commented
> why are you making this change?

I removed the extension for FHIR-43105 based on feedback from Lloyd. The other changes are for FHIR-41308 to fix the search parameter.

2024-07-29 22:35 UTC, grahamegrieve commented
That task + thread doesn't explain why this change, which I think is wrong. Not letting it into ballot

2025-09-10 16:15 UTC, closed without merging