Applied FHIR-46267
HL7/fhir-extensions pull request #119
Opened 2024-07-24 12:12 UTC by reubendaniels

2024-07-24 23:46 UTC, grahamegrieve commented
I think there should only be one reference with multiple targetProfiles

2024-07-25 02:05 UTC, lmckenzi requested changes
Reference should only be there once with multiple targetProfiles.

2024-07-25 03:38 UTC, reubendaniels commented
Thank you both.

@grahamegrieve, sorry I missed your original comment – for some reason I did not receive a notification (email or otherwise).

Multiple references now replaced with a single reference containing multiple targetProfiles.

2024-07-25 03:41 UTC, lmckenzi approved these changes

2024-07-25 03:54 UTC, merged