FHIR-43463 - Created new extension for improvement notation guidance
HL7/fhir-extensions pull request #64
Opened 2024-02-23 19:24 UTC by mholck

Quality Measures IG needed an extension added for improvement notation guidance. Created here and referenced in that IG.

2024-03-08 22:01 UTC, brynrhodes requested changes

2024-03-08 22:01 UTC, brynrhodes commented on input/definitions/Measure/StructureDefinition-cqf-improvementNotationGuidance.json
> +  "publisher": "Clinical Quality Information WG",
This should be "HL7 International / Clinical Quality Information"

2024-03-08 22:01 UTC, brynrhodes commented on input/definitions/Measure/StructureDefinition-cqf-improvementNotationGuidance.json
> +          "value": "http://www.hl7.org/Special/committees/cqi/index.cfm"
This shouldn't have the "/index.cfm" on it

2024-03-08 22:01 UTC, brynrhodes commented on input/definitions/Measure/StructureDefinition-cqf-improvementNotationGuidance.json
> +  "jurisdiction": [
Don't limit the jurisdiction to US, there's nothing specific to US usage here

2024-03-08 22:01 UTC, brynrhodes commented on input/definitions/Measure/StructureDefinition-cqf-improvementNotationGuidance.json
> +  "purpose": "**Purpose**\n\nMeasure consumers and implementers must be able to determine how to interpret a measure score.",
This is already a purpose element, suggest removing the **Purpose**\n\n bit and just providing the purpose. I'd go into a bit more detail here though, because as written, this is the purpose of improvementNotation, which is already an element on the measure and measure report. This is specifically to support:

In some cases, additional guidance is required to clearly communicate measure intent around improvement notation. For example, a measure looking at Ceasarean-section births may have an improvement notation of "decrease", but it is critical to be able to communicate that a measure score of 0 is not the intent.

2024-03-08 22:01 UTC, brynrhodes commented on input/definitions/Measure/StructureDefinition-cqf-improvementNotationGuidance.json
> +    }
Should allow this on MeasureReport and MeasureReport.group as well, to make sure it can be communicated in the measure report

2024-03-08 22:01 UTC, brynrhodes commented on input/definitions/Measure/StructureDefinition-cqf-improvementNotationGuidance.json
> +        "definition": "Explanation of improvement notation and how to interpret it.",
Consider, "Additional guidance on how to interpret the improvement notation of the measure"

2024-03-08 22:01 UTC, brynrhodes commented on input/definitions/Measure/StructureDefinition-cqf-improvementNotationGuidance.json
> +  "id": "cqf-improvementNotationGuidance",
Add the extensions to indicate wg ownership (cqi), fmm status (1), and standards-status (trial-use) See some of the other extensions for examples

2024-03-12 13:37 UTC, mholck commented
Changes made

2024-04-01 22:36 UTC, grahamegrieve approved these changes
ok

2024-04-01 22:38 UTC, merged