FHIR-43562 - add extensions for version specific values
HL7/fhir-extensions pull request #66
Opened 2024-03-06 20:11 UTC by grahamegrieve

2024-03-07 03:44 UTC, lmckenzi requested changes
Why is the context for the extensions all elements?  Shouldn't it be ElementDefinition and maybe a few sub-elements of it?  It would make zero sense outside canonical resources for sure.  Would feel much more comfortable enumerating allowed locations and extending as we need.  In particular, software is only going to look for this in certain places.  If someone asks for a new context, that's our cue to update the software to actually check for this.

2024-03-07 04:07 UTC, grahamegrieve commented
I'm using it a whole lot of places in the cross-version definitions, ones you haven't thought of. Let's leave it open while I finish that work, and we'll narrow it done when we do the next milestone release

2024-03-11 11:44 UTC, grahamegrieve commented
@lmckenzi ping on this

2024-03-11 21:06 UTC, lmckenzi approved these changes

2024-03-11 21:09 UTC, merged